config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#show'

  get 'index', to: 'home#index'

  resources :users do
    resources :items, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @user = current_user
    @item = @user.items.build(item_params)

    if @item.save
  		flash[:notice] = "Task was saved."
  		redirect_to root_path
  	else
  		flash.now[:alert] = "There was an error. please try again"
  		render :new
  	end
  end

  def destroy
    @item = Item.find(params[:id])
    if !@item.destroy
      flash.now[:alert] = "There was a problem deleting the task."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if !current_user
      redirect_to index_path
    else
      if params.has_key?(:id)
        if params[:id] != current_user.id.to_s
          flash[:alert] = "You may not access that page."
          redirect_to root_path
        else
          @items = Item.where(user_id: params[:id])
          @user = User.find(params[:id])
        end
      else
        @items = Item.where(user_id: current_user)
        @user = User.find(current_user.id)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Hello, Welcome to Blocitoff</h1>
<p>Sign in to get started being productive!</p>

app/views/items/_form.html.erb
<%= bootstrap_form_for [current_user, @item] do |f| %>
  <%= f.text_field :name, placeholder: "Enter the task", autofocus: true %>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/items/_item.html.erb
<p id="<%= item.id %>">
  <small><%= distance_of_time_in_words(Time.now, item.created_at + 7.days) + " before deletion" %></small>
  <br>
  <% if item.user == current_user %>
    <%= link_to "", user_item_path(user_id: current_user.id, id: item.id), remote: true, method: :delete, class: 'glyphicon glyphicon-ok', style: 'color:#1d600e;' %>
  <% end %>
  &nbsp;<%= item.name %>
</p>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
    $('#<%= @item.id %>').hide();
<% end %>

app/views/items/new.html.erb
<h1>New Task</h1>

<div class="row">
<div class="col-md-6">
  <%= render 'form' %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>blocmetrics.report('loaded');</script>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <ul class="nav nav-tabs">
            <% if user_signed_in? %>
              <li> <%= link_to "Home", user_path(current_user.id) %> </li>
              <li class="pull-right"><%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %></li>
              <li class="pull-right"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <li class="pull-right user-info">Signed in as: <strong> <%= current_user.email %> </strong></li>

            <% else %>
              <li> <%= link_to "Home", root_path %> </li>
              <li class="pull-right"><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
              <li class="pull-right"><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
            <% end %>
        </ul>
     </nav>


      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

  <div class="container">
    	<%= yield %>
	</div>

  </body>

</html>

app/views/users/show.html.erb
<h1>User: <%= @user.email %></h1>

<p>Account created: <%= current_user.created_at %></p>
<p>Account updated: <%= current_user.updated_at %></p>
<p>Account email address: <%= @user.email %></p>
<%= link_to 'Add item', new_user_item_path(@user), class: 'btn btn-default' %>
<h2>Tasks</h2>
<% @items.each do |item| %>
  <%= render item %>
<% end %>